services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  

  node-app:
    build: .
    image: robel1991/node-app
    environment:
      - PORT=5000
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password
    volumes:
      - mongo-dbs:/data/db  

  mongosh:
    image: mongo:7.0
    entrypoint: ["mongosh", "mongodb://admin:Password@mongo:27017/?authSource=admin"]
    depends_on:
      - mongo
  redis:
    image: redis

volumes:
  mongo-dbs:   
