version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"

  node-app:
    build: 
      context: .
      args: 
        - NODE_ENV=development 
    volumes:
     - ./:/app
     - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=admin
      - MONGO_PASSWORD=Password
      - REDIS_SESSION=my-secret
    command: npm run dev  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Password
      
